[project]
name = "tcc-ibn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "genai>=2.1.0",
    "google>=3.0.0",
    "google-genai>=1.46.0",
    "mininet>=2.3.0.dev6",
    "pygame>=2.6.1",
]
