[project]
name = "tcc-ibn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mininet>=2.3.0.dev6",
    "pygame>=2.6.1",
]
